### ISSUE TITLE
Flaky TestRoutingGroupSelector.testByRoutingRulesEngineFileChange

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino-gateway#123]
https://github.com/trinodb/trino-gateway/actions/runs/7361226191/job/20038470483?pr=117
```
Error:  io.trino.gateway.ha.router.TestRoutingGroupSelector.testByRoutingRulesEngineFileChange -- Time elapsed: 0.007 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <etl2> but was: <etl>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at io.trino.gateway.ha.router.TestRoutingGroupSelector.testByRoutingRulesEngineFileChange(TestRoutingGroupSelector.java:138)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino-gateway/actions/runs/7373251027/job/20062272299

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino-gateway/actions/runs/7373338926/job/20062427799?pr=131

**Comment by ebyhr** [comment]
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#lastModified()
> While the unit of time of the return value is milliseconds, the granularity of the value depends on the underlying file system and may be larger. For example, some file systems use time stamps in units of seconds.

```
2024-01-11T02:07:11.3585818Z INFO  [2024-01-11 02:07:11,349] io.trino.gateway.ha.router.TestRoutingGroupSelector: etl rule file created at: 1704938831345
2024-01-11T02:07:11.3588464Z INFO  [2024-01-11 02:07:11,351] io.trino.gateway.ha.router.TestRoutingGroupSelector: etl2 rule file created at: 1704938831345
2024-01-11T02:07:11.3819464Z [ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.239 s <<< FAILURE! -- in io.trino.gateway.ha.router.TestRoutingGroupSelector
2024-01-11T02:07:11.3822160Z [ERROR] io.trino.gateway.ha.router.TestRoutingGroupSelector.testByRoutingRulesEngineFileChange -- Time elapsed: 0.008 s <<< FAILURE!
2024-01-11T02:07:11.3824065Z org.opentest4j.AssertionFailedError: expected: not equal but was: <1704938831345>
2024-01-11T02:07:11.3825566Z 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
2024-01-11T02:07:11.3827210Z 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
2024-01-11T02:07:11.3828752Z 	at org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:277)
2024-01-11T02:07:11.3830146Z 	at org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:119)
2024-01-11T02:07:11.3831534Z 	at org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:111)
2024-01-11T02:07:11.3832843Z 	at org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:2117)
2024-01-11T02:07:11.3834587Z 	at io.trino.gateway.ha.router.TestRoutingGroupSelector.testByRoutingRulesEngineFileChange(TestRoutingGroupSelector.java:159)
2024-01-11T02:07:11.3836224Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-01-11T02:07:11.3837176Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-01-11T02:07:11.3838156Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
https://github.com/trinodb/trino-gateway/actions/runs/7483283474/job/20368283064

cc: @willmostly
