### ISSUE TITLE
Trailing / in backend ProxyTo URL causes routing error

### ISSUE THREAD

**Issue by willmostly** [trinodb/trino-gateway#564]
A trailing slash in the proxyTo URL, e.g. 
```
{"name": "my-proxy-target", "routingGroup":"adhoc", "ProxyTo": "https://my-proxy-target.io/", "ExternalUrl": "https://my-proxy-target.io/"}
```
 will produce a URL like https://my-proxy-target.io//v1/statement. This will in turn produce an obscure error message such as 

```
org.eclipse.jetty.http.BadMessageException: 400: Ambiguous URI empty segment at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.headerComplete(HttpConnection.java:1194) at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:959) at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1350) at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1646) at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:575) at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:382) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99) at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311) at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164) at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by neshatadyen** [comment]
Thank you for sharing it! We're experimenting Trino Gateway and it would be difficult to find the issue for us if you haven't shared this
